### PR TITLE
fix order of catch blocks

### PR DESCRIPTION
**Pull request by arturpanteleev**
Change catch blocks for Throwable and Exception

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but this doesn't do anything. The behaviour before and after is the same.

**Comment by GrahamCampbell** [comment]
FYI, we need both for PHP 5 compatibility.

**Comment by 4n70w4** [comment]
Hi!

FYI, PHP 5.6 oficially stopped maintain 31 Dec 2018.
Other versions are not supported even longer.

https://www.php.net/eol.php

**Comment by arturpanteleev** [comment]
But what will you do if you want to separate logic of handling \Error(or any others not Exception implementations of Throwable) and \Excpetinon ? Without my correction behavior will not be correct!

**Comment by EdgarSedov** [comment]
> Hi!
> 
> FYI, PHP 5.6 oficially stopped maintain 31 Dec 2018. Other versions are not supported even longer.
> 
> https://www.php.net/eol.php

Btw, this seems quite reasonable to me. Can't we just tag another major version and drop it from support? Having php5 currently is simply unsafe for production, since it hasn't been getting any security fixes for more than 3 years now

**Pull request closed without merging**
