### PR TITLE
Dont test PHP on travis

### PR DESCRIPTION
**Pull request by Nyholm**
Only run HHVM

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
PHP 5.5.9 is no longer tested now.

**Comment by Nyholm** [comment]
What is special about that version? 

We do test on 5.5.x

**Comment by GrahamCampbell** [comment]
5.5.9 comes with Ubuntu 16.04 LTS, and also is the lowest version of PHP supported by some version of symfony. We wanna make sure that any bugs affecting that version of PHP don't break our tests.

**Comment by Nyholm** [comment]
I see. Okey.

I saw your PR. Thank you

**Pull request merged**
