### PR TITLE
Updating EachPromise to not call next until as late as possible.

### PR DESCRIPTION
**Pull request by mtdowling**
This commit updates EachPromise to call next() on the given iterator
only after filling promises and only when doing so would not advance the
iterator past the concurrency level. This allows generators to now
function correctly when the generator might not know whether or not
there are more results until after callbacks have been fired.

See https://github.com/guzzle/guzzle/issues/1108

@jeremeamia @jeskew

### CODE REVIEW

**Comment by jeremeamia** [comment]
Whoa, that is pretty cool. :+1:

**Comment by jeskew** [comment]
:+1:

**Comment by mtdowling** [comment]
I ran the unit and integration tests of the AWS SDK for PHP with this branch checked out, and everything passes. Merging.

**Comment by inkrement** [comment]
@mtdowling  This is great and I am using it instead of a Pool, but is there a way to use Middlewares (e.g. RetryMiddleware) with the EachPromise interface?

**Pull request merged**
